---
- hosts: all
  become: true
  tasks:
    - name: Update repositry index
      apt:
        update_cache: yes

    - name: Install Apache2 package
      apt:
        name: apache2
        state: absent
